api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":8080"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "church-planner-network"
  file:
    directory: "/etc/traefik/config"
    watch: true

metrics:
  prometheus:
    entryPoint: metrics
    addServicesLabels: true
    addEntryPointsLabels: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

tracing:
  jaeger:
    samplingServerURL: "http://jaeger:5778/sampling"
    localAgentHostPort: "jaeger:6831" 