apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: church-planner
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ${DOCKER_REGISTRY}/church-planner/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: church-planner-config
              key: postgres-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: church-planner-config
              key: postgres-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: church-planner-secrets
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: church-planner-secrets
              key: postgres-password
        - name: DB_NAME
          value: "auth_db"
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: church-planner-config
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: church-planner-config
              key: redis-port
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: church-planner-secrets
              key: jwt-secret
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: church-planner-config
              key: nats-url
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /api/auth/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/auth/health/ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: church-planner
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP 