global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'churches-service'
    static_configs:
      - targets: ['churches-service:3002']

  - job_name: 'members-service'
    static_configs:
      - targets: ['members-service:3003']

  - job_name: 'events-service'
    static_configs:
      - targets: ['events-service:3004']

  - job_name: 'scheduling-service'
    static_configs:
      - targets: ['scheduling-service:3005']

  - job_name: 'messaging-service'
    static_configs:
      - targets: ['messaging-service:3006']

  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:3007']

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml" 